Update README.rst
added what worked for me , still does not want to install because of 

gis@gis-VirtualBox:~/Downloads/OSMQA$ env/bin/python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools